### ISSUE TITLE
Windows Defender Antivirus detects your tool

### ISSUE THREAD

**Issue by sonicdcer** [KernelEquinox/SotN-Editor#4]
Windows Defender Antivirus detects a Trojan:Script/Wacatac.H!ml in your release binary

**Comment by sonicdcer** [comment]
![image](https://user-images.githubusercontent.com/96613413/209797104-7d47f1f3-110a-405b-95cb-5a531a45a1f0.png)

**Comment by KernelEquinox** [comment]
Microsoft has been made aware of the issue and has removed the program from their detection database.
